services:
  mimicer-client:
    container_name: mimicer-client
    build: ./mimicer-admin
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_HOST=${API_HOST}
      - VITE_API_KEY=${API_KEY}
    volumes:
      - ./ci/client.conf:/etc/nginx/conf.d/default.conf
      - ./ci/client.crt:/etc/ssl/certs/client.crt
      - ./ci/client.key:/etc/ssl/private/client.key
