services:
  admin-web:
    container_name: mimicer-admin
    build: ./mimicer-admin
    ports:
      - "3000:3000"
  api-server:
    container_name: mimicer-api-server
    build: ./mimicer-api-server
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - API_KEY=secret
      - DATABASE_URL=postgres://postgres:password@database:5432/mimicer-db
  database:
    container_name: mimicer-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mimicer-db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "mimicer-db"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
